#!/usr/bin/env python3
"""Generate the AI client briefings the brief requires, as a committed artefact.

    python scripts/generate_briefings.py [CLIENT_ID ...]

Writes docs/ai_briefings.md. Responses are cached to prompts/cache/, so re-running
this costs no API quota and works offline once the cache is populated.
"""

from __future__ import annotations

import logging
import sys
from pathlib import Path

logging.disable(logging.WARNING)

ROOT = Path(__file__).parents[1]
sys.path.insert(0, str(ROOT))

from ai import llm  # noqa: E402
from ai.briefing import generate_briefing  # noqa: E402
from ai.retrieval import get_scored_table  # noqa: E402

DEFAULT_CLIENTS = ["E09", "E01", "E16"]
OUTPUT = ROOT / "docs" / "ai_briefings.md"


def main() -> int:
    client_ids = sys.argv[1:] or DEFAULT_CLIENTS
    status = llm.provider_status()

    table = get_scored_table().set_index("client_id")
    sections: list[str] = []

    header = [
        "# AI-Generated Client Briefings",
        "",
        "**Team The Independent Variable** — Standard Bank × Data School Hackathon 2026",
        "",
        "Pre-meeting briefings for a Syn Bank coverage banker, written by a language",
        "model from figures computed by the wallet engine. The model is given an",
        "evidence block and instructed to reuse those figures verbatim; it never",
        "supplies a number of its own. Every output below was then re-read by",
        "`ai.llm.verify_grounding`, which flags any rand amount or percentage that did",
        "not appear in the evidence.",
        "",
        f"- Provider: `{status['provider']}`",
        f"- Model: `{status['model']}`",
        "- Prompts and raw outputs: `prompts/logs/`",
        "- Regenerate with: `python scripts/generate_briefings.py`",
        "",
        "---",
        "",
    ]

    for client_id in client_ids:
        payload = generate_briefing(client_id)
        if client_id not in table.index:
            print(f"  skipped {client_id}: not in the scored portfolio", file=sys.stderr)
            continue
        row = table.loc[client_id]

        warnings = payload.get("groundingWarnings") or []
        sections.extend(
            [
                f"## {row['client_name']} ({client_id}) — {row['sector_display']}",
                "",
                f"> Rank {int(row['rank'])} of {len(table)} · "
                f"estimated share {float(row['syn_share']) * 100:.1f}% · "
                f"annual fee opportunity R{float(row['revenue_opportunity']) / 1e6:,.0f}M · "
                f"largest gap in {row['top_pillar']}",
                "",
                payload["summary"],
                "",
                "**Key signals**",
                "",
                *[f"- {s}" for s in payload["keySignals"]],
                "",
                "**Recommended agenda**",
                "",
                *[f"- {a}" for a in payload["recommendedAgenda"]],
                "",
            ]
        )
        if payload.get("risk"):
            sections.extend([f"**Risk.** {payload['risk']}", ""])

        sections.extend(
            [
                f"<sub>Generated by `{payload['generatedBy']}`"
                + (" (from cache)" if payload.get("cached") else "")
                + f" · grounding warnings: {', '.join(warnings) if warnings else 'none'}</sub>",
                "",
                "---",
                "",
            ]
        )
        flag = f"  warnings={warnings}" if warnings else ""
        print(f"  {client_id:<5} {payload['generatedBy']}{flag}")

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text("\n".join(header + sections), encoding="utf-8")
    print(f"\nwrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
